version: '3.8'

services:
  alpha-fitness:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - PORT=3000
      - HOST=0.0.0.0
    restart: always
