/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as StoreRouteImport } from './routes/store'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RemindersRouteImport } from './routes/reminders'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MembersRouteImport } from './routes/members'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as BranchesRouteImport } from './routes/branches'
import { Route as BackupRouteImport } from './routes/backup'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AttendanceRouteImport } from './routes/attendance'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MembersNewRouteImport } from './routes/members.new'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RemindersRoute = RemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesRoute = BranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupRoute = BackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendanceRoute = AttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersNewRoute = MembersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => MembersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/attendance': typeof AttendanceRoute
  '/auth': typeof AuthRoute
  '/backup': typeof BackupRoute
  '/branches': typeof BranchesRoute
  '/expenses': typeof ExpensesRoute
  '/help': typeof HelpRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/reminders': typeof RemindersRoute
  '/reports': typeof ReportsRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/store': typeof StoreRoute
  '/todos': typeof TodosRoute
  '/tools': typeof ToolsRoute
  '/members/new': typeof MembersNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/attendance': typeof AttendanceRoute
  '/auth': typeof AuthRoute
  '/backup': typeof BackupRoute
  '/branches': typeof BranchesRoute
  '/expenses': typeof ExpensesRoute
  '/help': typeof HelpRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/reminders': typeof RemindersRoute
  '/reports': typeof ReportsRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/store': typeof StoreRoute
  '/todos': typeof TodosRoute
  '/tools': typeof ToolsRoute
  '/members/new': typeof MembersNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/attendance': typeof AttendanceRoute
  '/auth': typeof AuthRoute
  '/backup': typeof BackupRoute
  '/branches': typeof BranchesRoute
  '/expenses': typeof ExpensesRoute
  '/help': typeof HelpRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/reminders': typeof RemindersRoute
  '/reports': typeof ReportsRoute
  '/schedule': typeof ScheduleRoute
  '/settings': typeof SettingsRoute
  '/store': typeof StoreRoute
  '/todos': typeof TodosRoute
  '/tools': typeof ToolsRoute
  '/members/new': typeof MembersNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/attendance'
    | '/auth'
    | '/backup'
    | '/branches'
    | '/expenses'
    | '/help'
    | '/landing'
    | '/login'
    | '/members'
    | '/onboarding'
    | '/reminders'
    | '/reports'
    | '/schedule'
    | '/settings'
    | '/store'
    | '/todos'
    | '/tools'
    | '/members/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/attendance'
    | '/auth'
    | '/backup'
    | '/branches'
    | '/expenses'
    | '/help'
    | '/landing'
    | '/login'
    | '/members'
    | '/onboarding'
    | '/reminders'
    | '/reports'
    | '/schedule'
    | '/settings'
    | '/store'
    | '/todos'
    | '/tools'
    | '/members/new'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/attendance'
    | '/auth'
    | '/backup'
    | '/branches'
    | '/expenses'
    | '/help'
    | '/landing'
    | '/login'
    | '/members'
    | '/onboarding'
    | '/reminders'
    | '/reports'
    | '/schedule'
    | '/settings'
    | '/store'
    | '/todos'
    | '/tools'
    | '/members/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AttendanceRoute: typeof AttendanceRoute
  AuthRoute: typeof AuthRoute
  BackupRoute: typeof BackupRoute
  BranchesRoute: typeof BranchesRoute
  ExpensesRoute: typeof ExpensesRoute
  HelpRoute: typeof HelpRoute
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  MembersRoute: typeof MembersRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  RemindersRoute: typeof RemindersRoute
  ReportsRoute: typeof ReportsRoute
  ScheduleRoute: typeof ScheduleRoute
  SettingsRoute: typeof SettingsRoute
  StoreRoute: typeof StoreRoute
  TodosRoute: typeof TodosRoute
  ToolsRoute: typeof ToolsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reminders': {
      id: '/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof RemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches': {
      id: '/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof BranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backup': {
      id: '/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof BackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendance': {
      id: '/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/new': {
      id: '/members/new'
      path: '/new'
      fullPath: '/members/new'
      preLoaderRoute: typeof MembersNewRouteImport
      parentRoute: typeof MembersRoute
    }
  }
}

interface MembersRouteChildren {
  MembersNewRoute: typeof MembersNewRoute
}

const MembersRouteChildren: MembersRouteChildren = {
  MembersNewRoute: MembersNewRoute,
}

const MembersRouteWithChildren =
  MembersRoute._addFileChildren(MembersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AttendanceRoute: AttendanceRoute,
  AuthRoute: AuthRoute,
  BackupRoute: BackupRoute,
  BranchesRoute: BranchesRoute,
  ExpensesRoute: ExpensesRoute,
  HelpRoute: HelpRoute,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  MembersRoute: MembersRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  RemindersRoute: RemindersRoute,
  ReportsRoute: ReportsRoute,
  ScheduleRoute: ScheduleRoute,
  SettingsRoute: SettingsRoute,
  StoreRoute: StoreRoute,
  TodosRoute: TodosRoute,
  ToolsRoute: ToolsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
